### ISSUE TITLE
Deprecated function: preg_match(): Passing null to parameter

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_calculator#3]
@aoristos filed a PR for this issue.

> warning:Deprecated function: preg_match(): Passing null to parameter https://github.com/backdrop-contrib/webform_calculator/pull/2 ($subject) of type string is deprecated in WebformEvalMath->nfx() (line 217 of /var/www/html/modules/webform_calculator/matheval.class.php).

The suggestion: 

> solution: add a null coalescing operator for parameter # 2 in line 217

@argiepiano pointed out that Backdrop officially supports PHP 5.6 at the moment, so we should not use the null coalescing operator (which was added in PHP 7.0), and @aoristos modified the PR to include a check for the PHP version.

**Comment by laryn** [comment]
I can replicate by creating a form with two integer fields that get multiplied in a formula field, and then submitting the form.

**Comment by argiepiano** [comment]
Added a comment to the PR.

**Comment by laryn** [comment]
I made a new release and credited the two of you in the release notes: 
 - https://github.com/backdrop-contrib/webform_calculator/releases/tag/1.x-2.1.1

Thanks for finding the issue and submitting a PR, @aoristos -- and for pitching in to polish it up @argiepiano.
